language: java
jdk:
- openjdk8
script: mvn clean verify

deploy:
  provider: heroku
  api_key:
    secure: MA53sVyFVFfrIbhFSwtq/O+e6+GVHTrBL6Jf+bJxTFAQWK2cqxwgRvuARb73wxxY69WUbFAhjJRIhdW0JkJY6mX2R7L6PWtcnmta6aCCWZR+BEOQd1xtnxRw9UCZ1xDUyNhqOOKOgtB6c4+5Ii07gU11DCmLc54S3NIra8YPl1z5vs40dZoIuBeGhHFupeA56mEd8v+30Avov29ocFSNI5ZAWAzMRnLOeq5XOUZQgBpZQaGpgd1tCUe1YnLzn7x9wEfsDAyMLIFv1kwEXQiZGHRiFzGWETvpJWqE9KcBZXTSnXI2SzUtuSKSCjDWBeNmUDfdYl8k209U/CxnJRRkcVWZLsHR4OmWO87W58mxkR3AzO5myHim9nWwe3MzQbOFI6MF4oeMN2HhnhpB9ANsBuXYW/o9sZeLMV2BNvy+36x89cUEgeyaTHyfEVPsMTwao0z4I/w5vJyZjm4yq6NTyPLNeBjHDnOOnGDUuGfn9qDt3FuKZ5M6Q4TBjUi8xahmejxTOTyKxbkQ4RaWZ2f/sP8o+3nAZptOqi58uFIIlSr+tHt5xE3mCYICB0/wgXLhTLkl5we6pLn9nRm5q42VoQcshfhgKhsI9RyyS/RlDbFemJaDlR/ix2whIiv2qi8V8CM3vNWINPDWizL99JrtDVxunff8689o3TskXd4yuYU=
   app: cicd-sample-java
